(function() {var implementors = {};
implementors['dns_parser'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dns_parser/enum.Type.html' title='dns_parser::Type'>Type</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dns_parser/enum.QueryType.html' title='dns_parser::QueryType'>QueryType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dns_parser/enum.Class.html' title='dns_parser::Class'>Class</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dns_parser/enum.QueryClass.html' title='dns_parser::QueryClass'>QueryClass</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dns_parser/enum.Opcode.html' title='dns_parser::Opcode'>Opcode</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dns_parser/enum.ResponseCode.html' title='dns_parser::ResponseCode'>ResponseCode</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dns_parser/struct.Name.html' title='dns_parser::Name'>Name</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dns_parser/struct.Header.html' title='dns_parser::Header'>Header</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
